import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const distDir = join(root, 'dist');

const mainFiles = [
  'src/main/utils.js',
  'src/main/selection.js',
  'src/main/semantic-targets.js',
  'src/main/settings.js',
  'src/main/tools/batch-edit.js',
  'src/main/tools/design-qa.js',
  'src/main/tools/duplicate.js',
  'src/main/commands.js',
  'src/main/index.js',
];

const uiFiles = [
  'src/ui/tools.js',
  'src/ui/figma-bridge.js',
  'src/ui/model-client.js',
  'src/ui/edit-plan.js',
  'src/ui/tool-loop.js',
  'src/ui/settings-panel.js',
  'src/ui/app.js',
];

mkdirSync(distDir, { recursive: true });

const mainBundle = buildScript(mainFiles);
writeFileSync(join(distDir, 'main.js'), mainBundle, 'utf8');

const css = readFileSync(join(root, 'src/ui/styles.css'), 'utf8');
const uiBundle = buildScript(uiFiles);
const html = readFileSync(join(root, 'src/ui/index.html'), 'utf8')
  .replace('__STYLE__', css)
  .replace('__SCRIPT__', uiBundle);
writeFileSync(join(distDir, 'ui.html'), html, 'utf8');

console.log('Built dist/main.js and dist/ui.html.');

function buildScript(files) {
  return [
    '// Generated by scripts/build.mjs. Do not edit directly.',
    ...files.map((file) => {
      const source = readFileSync(join(root, file), 'utf8');
      return [
        `\n// ${file}`,
        stripModules(source),
      ].join('\n');
    }),
    '',
  ].join('\n');
}

function stripModules(source) {
  return source
    .replace(/import[\s\S]*?from\s+['"][^'"]+['"];\n/g, '')
    .replace(/\bexport\s+/g, '');
}
