import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, context } from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const distDir = join(root, 'dist');
const watchMode = process.argv.includes('--watch');

mkdirSync(distDir, { recursive: true });

const sharedOptions = {
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2018',
  legalComments: 'none',
  logLevel: 'info',
};

const mainOptions = {
  ...sharedOptions,
  entryPoints: [join(root, 'src/main/index.js')],
  outfile: join(distDir, 'main.js'),
  banner: { js: '// Generated by scripts/build.mjs. Do not edit directly.' },
};

const uiOptions = {
  ...sharedOptions,
  entryPoints: [join(root, 'src/ui/app.js')],
  write: false,
  plugins: [uiHtmlPlugin()],
};

if (watchMode) {
  const mainContext = await context(mainOptions);
  const uiContext = await context(uiOptions);
  await Promise.all([mainContext.watch(), uiContext.watch()]);
  console.log('Watching source files and rebuilding dist/.');
} else {
  await Promise.all([build(mainOptions), build(uiOptions)]);
  console.log('Built dist/main.js and dist/ui.html.');
}

function uiHtmlPlugin() {
  const cssPath = join(root, 'src/ui/styles.css');
  const templatePath = join(root, 'src/ui/index.html');
  return {
    name: 'inline-ui-html',
    setup(esbuild) {
      esbuild.onLoad({ filter: /src\/ui\/app\.js$/ }, (args) => ({
        contents: readFileSync(args.path, 'utf8'),
        loader: 'js',
        resolveDir: dirname(args.path),
        watchFiles: [cssPath, templatePath],
      }));
      esbuild.onEnd((result) => {
        if (result.errors.length) return;
        const script = result.outputFiles?.[0]?.text;
        if (!script) throw new Error('esbuild did not produce the UI JavaScript bundle.');

        const css = readFileSync(cssPath, 'utf8');
        const template = readFileSync(templatePath, 'utf8');
        const html = template
          .replace('__STYLE__', css)
          .replace('__SCRIPT__', `// Generated by scripts/build.mjs. Do not edit directly.\n${script}`);
        writeFileSync(join(distDir, 'ui.html'), html, 'utf8');
      });
    },
  };
}
