import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const files = [
  'manifest.json',
  'dist/main.js',
  'dist/ui.html',
  'src/main/index.js',
  'src/main/commands.js',
  'src/main/settings.js',
  'src/main/selection.js',
  'src/main/semantic-targets.js',
  'src/main/tools/batch-edit.js',
  'src/main/tools/design-qa.js',
  'src/main/tools/duplicate.js',
  'src/ui/index.html',
  'src/ui/styles.css',
  'src/ui/app.js',
  'src/ui/figma-bridge.js',
  'src/ui/edit-plan.js',
  'src/ui/model-client.js',
  'src/ui/settings-panel.js',
  'src/ui/tool-loop.js',
  'src/ui/tools.js',
  'scripts/build.mjs',
  'docs/architecture.md',
  'docs/product-engineering-handbook.md',
  'SECURITY.md',
  'README.md',
];

for (const file of files) {
  readFileSync(join(root, file), 'utf8');
}

const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));
if (manifest.main !== 'dist/main.js') throw new Error('manifest.main must point to dist/main.js');
if (manifest.ui !== 'dist/ui.html') throw new Error('manifest.ui must point to dist/ui.html');

const main = readFileSync(join(root, 'dist/main.js'), 'utf8');
const ui = readFileSync(join(root, 'dist/ui.html'), 'utf8');
const allText = files.map((file) => readFileSync(join(root, file), 'utf8')).join('\n');

execFileSync(process.execPath, ['--check', join(root, 'dist/main.js')], { stdio: 'pipe' });

if (/\bimport\b|\bexport\b/.test(main)) throw new Error('dist/main.js must be bundled without ESM syntax.');
if (ui.includes('__STYLE__') || ui.includes('__SCRIPT__')) throw new Error('dist/ui.html contains unbuilt placeholders.');
if (!ui.includes('Generated by scripts/build.mjs')) throw new Error('dist/ui.html does not contain the generated UI bundle.');

const scriptMatch = ui.match(/<script>\s*([\s\S]*?)\s*<\/script>/);
if (!scriptMatch) throw new Error('dist/ui.html must contain an inline script.');
if (/\bimport\b|\bexport\b/.test(scriptMatch[1])) throw new Error('dist/ui.html must be bundled without ESM syntax.');
new Function(scriptMatch[1]);

for (const forbidden of ['vip-brain.qiyi.domain', 'vip-figma-server.qiyi.domain', 'FIXED_API_TOKEN']) {
  if (allText.includes(forbidden)) {
    throw new Error(`Forbidden internal token/domain found: ${forbidden}`);
  }
}

console.log('Figma Batch AI project check passed.');
