import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { COMMAND_NAMES, PREVIEW_HANDLER_NAMES } from '../src/main/command-names.js';
import { COMMANDS } from '../src/main/commands.js';
import { TOOL_REGISTRY } from '../src/shared/tool-registry.js';

const root = new URL('..', import.meta.url).pathname;
const files = [
  'package.json',
  'manifest.json',
  'dist/main.js',
  'dist/ui.html',
  'eslint.config.js',
  'prettier.config.js',
  'vitest.config.js',
  '.github/workflows/ci.yml',
  ...walkFiles('src'),
  ...walkFiles('scripts'),
  ...walkFiles('tests'),
  'docs/architecture.md',
  'docs/product-engineering-handbook.md',
  'SECURITY.md',
  'README.md',
];

for (const file of files) {
  readFileSync(join(root, file), 'utf8');
}

const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));
if (manifest.main !== 'dist/main.js') throw new Error('manifest.main must point to dist/main.js');
if (manifest.ui !== 'dist/ui.html') throw new Error('manifest.ui must point to dist/ui.html');

const main = readFileSync(join(root, 'dist/main.js'), 'utf8');
const ui = readFileSync(join(root, 'dist/ui.html'), 'utf8');
const sourceFiles = [
  ...walkFiles('src'),
  ...walkFiles('scripts').filter((file) => file !== 'scripts/check.mjs'),
  ...walkFiles('docs'),
  'README.md',
  'SECURITY.md',
  'manifest.json',
];
const allText = sourceFiles.map((file) => readFileSync(join(root, file), 'utf8')).join('\n');

execFileSync(process.execPath, ['--check', join(root, 'dist/main.js')], { stdio: 'pipe' });

if (/\bimport\b|\bexport\b/.test(main)) throw new Error('dist/main.js must be bundled without ESM syntax.');
if (ui.includes('__STYLE__') || ui.includes('__SCRIPT__'))
  throw new Error('dist/ui.html contains unbuilt placeholders.');
if (!ui.includes('Generated by scripts/build.mjs'))
  throw new Error('dist/ui.html does not contain the generated UI bundle.');

const scriptMatch = ui.match(/<script>\s*([\s\S]*?)\s*<\/script>/);
if (!scriptMatch) throw new Error('dist/ui.html must contain an inline script.');
if (/\bimport\b|\bexport\b/.test(scriptMatch[1]))
  throw new Error('dist/ui.html must be bundled without ESM syntax.');
new Function(scriptMatch[1]);

for (const forbidden of ['vip-brain.qiyi.domain', 'vip-figma-server.qiyi.domain', 'FIXED_API_TOKEN']) {
  if (allText.includes(forbidden)) {
    throw new Error(`Forbidden internal token/domain found: ${forbidden}`);
  }
}

assertToolRegistryConsistency();

console.log('Figma Batch AI project check passed.');

function assertToolRegistryConsistency() {
  assertUnique(COMMAND_NAMES, 'command');
  assertUnique(PREVIEW_HANDLER_NAMES, 'preview handler');
  const handlerNames = Object.keys(COMMANDS);
  if (
    handlerNames.length !== COMMAND_NAMES.length ||
    handlerNames.some((name) => !COMMAND_NAMES.includes(name))
  ) {
    throw new Error('COMMANDS handlers must match COMMAND_NAMES.');
  }

  const toolNames = TOOL_REGISTRY.map(({ name }) => name);
  assertUnique(toolNames, 'LLM tool');

  for (const metadata of TOOL_REGISTRY) {
    if (!COMMAND_NAMES.includes(metadata.name)) {
      throw new Error(`LLM tool is missing from command handlers: ${metadata.name}`);
    }
    if (metadata.preview !== false && !PREVIEW_HANDLER_NAMES.includes(metadata.preview)) {
      throw new Error(`LLM tool has an unsupported preview strategy: ${metadata.name}`);
    }
    if (metadata.confirm !== (metadata.preview !== false)) {
      throw new Error(`LLM tool confirmation and preview metadata disagree: ${metadata.name}`);
    }
  }
}

function assertUnique(names, label) {
  if (new Set(names).size !== names.length) throw new Error(`Duplicate ${label} name found.`);
}

function walkFiles(directory) {
  const out = [];
  for (const entry of readdirSync(join(root, directory), { withFileTypes: true })) {
    const relative = join(directory, entry.name);
    if (entry.isDirectory()) out.push(...walkFiles(relative));
    else out.push(relative);
  }
  return out;
}
